version: '3.2'

services:

  todo-web-app:
    image: todo-web-app:latest
    container_name: todo-web-app
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
