export const ADD_TOAST = 'ADD_TOAST'
export const REMOVE_TOAST_BY_UUID = 'REMOVE_TOAST_BY_UUID'
export const SET_USER_NOTES = "SET_USER_NOTES"
export const SET_LOADING_USER_NOTES = "SET_LOADING_USER_NOTES"
export const SET_MAIN_USER_NOTES_INFO = "SET_MAIN_USER_NOTES_INFO"
export const SET_LOADING_MAIN_USER_NOTES_INFO = "SET_LOADING_MAIN_USER_NOTES_INFO"
export const SET_NEED_RELOAD_USER_MAIN_NOTES_INFO = "SET_NEED_RELOAD_USER_MAIN_NOTES_INFO"